[package]
name = "rdash"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rdash"
path = "src/main.rs"

[dependencies]
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
clap = { version = "4.0", features = ["derive"] }
